/*
Module 6: Networking - gRPC Concepts (Mock Implementation)

Demonstrates the gRPC pattern WITHOUT external dependencies:
  - Service definition (what .proto generates → Go interface)
  - Server implementation (struct satisfying the interface)
  - Client stub (calls through the interface, could be local or remote)
  - Request/Response types (like protobuf messages)
  - Interceptors/middleware pattern (like gRPC interceptors)

Key insight: gRPC is essentially: define interface in .proto → generate
Go interface + client stub → implement server → transport handles the rest.
This file shows the PATTERN; real gRPC adds code generation + HTTP/2.

Run: go run main.go
*/
package main

import (
	"context"
	"fmt"
	"log"
	"time"
)

// --- "Protobuf" message types (normally generated by protoc) ---

type GetUserRequest struct {
	UserID string
}

type User struct {
	ID    string
	Name  string
	Email string
}

type CreateUserRequest struct {
	Name  string
	Email string
}

// --- Service interface (generated from .proto service definition) ---

type UserServiceServer interface {
	GetUser(ctx context.Context, req *GetUserRequest) (*User, error)
	CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error)
}

// --- Server implementation ---

type userServiceImpl struct {
	users map[string]*User
	nextID int
}

func (s *userServiceImpl) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	user, ok := s.users[req.UserID]
	if !ok {
		return nil, fmt.Errorf("user %s not found", req.UserID)
	}
	return user, nil
}

func (s *userServiceImpl) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	s.nextID++
	user := &User{
		ID:    fmt.Sprintf("user_%d", s.nextID),
		Name:  req.Name,
		Email: req.Email,
	}
	s.users[user.ID] = user
	return user, nil
}

// --- Interceptor (like gRPC UnaryInterceptor) ---

type UnaryInterceptor func(ctx context.Context, method string, req interface{}, handler func(ctx context.Context) (interface{}, error)) (interface{}, error)

func loggingInterceptor(ctx context.Context, method string, req interface{}, handler func(ctx context.Context) (interface{}, error)) (interface{}, error) {
	start := time.Now()
	log.Printf("[gRPC] → %s req=%+v", method, req)
	resp, err := handler(ctx)
	log.Printf("[gRPC] ← %s duration=%v err=%v", method, time.Since(start), err)
	return resp, err
}

// --- Client stub (calls through interface, interceptor wraps calls) ---

type userServiceClient struct {
	service     UserServiceServer
	interceptor UnaryInterceptor
}

func (c *userServiceClient) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	resp, err := c.interceptor(ctx, "UserService/GetUser", req, func(ctx context.Context) (interface{}, error) {
		return c.service.GetUser(ctx, req)
	})
	if err != nil {
		return nil, err
	}
	return resp.(*User), nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	resp, err := c.interceptor(ctx, "UserService/CreateUser", req, func(ctx context.Context) (interface{}, error) {
		return c.service.CreateUser(ctx, req)
	})
	if err != nil {
		return nil, err
	}
	return resp.(*User), nil
}

func main() {
	// "Register" service (like grpc.RegisterService)
	server := &userServiceImpl{users: make(map[string]*User)}

	// Create client with interceptor (like grpc.Dial with options)
	client := &userServiceClient{
		service:     server,
		interceptor: loggingInterceptor,
	}

	ctx := context.Background()

	// Use the service through the client stub
	created, err := client.CreateUser(ctx, &CreateUserRequest{
		Name: "Alice", Email: "alice@example.com",
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Created: %+v\n", created)

	fetched, err := client.GetUser(ctx, &GetUserRequest{UserID: created.ID})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Fetched: %+v\n", fetched)

	// Demonstrate error case
	_, err = client.GetUser(ctx, &GetUserRequest{UserID: "nonexistent"})
	fmt.Printf("Error case: %v\n", err)
}
